---
title: "Getting started with the brms package"
format: html
editor: visual
---
## Load package

```{r}
library(brms)
library("readr")

trials <- read_csv("output_ucap/trials.csv")
head(trials)
```

## Example: Poisson regression model

```{r}
fit1 <- brm(count ~ zAge + zBase * Trt + (1|patient),
            data = epilepsy, family = poisson())
```

### Results 

```{r}
summary(fit1)
```


### Plot

```{r}
plot(fit1, variable = c("b_Trt1", "b_zBase"))
```


## Test using the UCAP Data set

### Regularizing Priors???

```{r}
mod <- brm(N2 ~ 1,
           data = trials, 
           family = gaussian(),
           prior = c(prior(uniform(-100, 100), class = Intercept, lb = -100, ub = 100),
           prior(uniform(0, 50), class = sigma)))
```


#### Results

```{r}
summary(mod)
```

#### Plot

```{r}
plot(mod)
```

### Informative priors

```{r}
mod2 <- brm(N2 ~ 1,
           data = trials, 
           family = gaussian(),
           prior = c(prior(normal(0, 10), class = Intercept),
           prior(normal(0, 5), class = sigma)))
```

#### Results

```{r}
summary(mod2)
```

#### Plot

```{r}
plot(mod2)
```



