---
title: "Cross validation - N400"
format: html
editor: visual
---

## Load packages

```{r}
library(brms)
library(readr)
library(bayesplot)
library(ggplot2)
library(dplyr)
library(rstan)
library(bridgesampling)
```

```{r}
trials_n400 <- read_csv("output_n400/trials.csv")
```

Add column for condition

```{r}
trials_cond <- trials_n400 |>
  mutate(condition = ifelse(value <= 212, "related", "unrelated"))
head(trials_cond)
```

## Cross validation for Correlation Model

```{r}
prior_0cor <- c(prior(normal(0, 10), class = Intercept), # grand mean
                prior(normal(0, 10), class = b, coef = conditionunrelated), # grand beta
                prior(normal(0, 50), class = sigma), # within person variation
                prior(normal(0, 20), class = sd, coef = Intercept, group = participant_id), # between person variation in mean 
                prior(normal(0, 20), class = sd, coef = conditionunrelated, group = participant_id), # between person variation in slope
                prior(lkj(2), class = cor, group = participant_id)) # correlation between random intercept and random slope
```

### Model 1

```{r}
mod_n400_cor_1 <- brm(N400 ~ 1 + condition + (1 + condition | participant_id),
                         data = trials_cond, 
                         prior = prior_0cor,
                         family = gaussian(), # default
                         cores = 4) 
```

### Setting up null model

```{r}
mod_n400_cor_0 <- brm(N400 ~ 1 + (1 + condition | participant_id),
                      data = trials_cond, 
                      prior = prior_0cor[prior_0cor$class != "b", ],
                      family = gaussian(), # default
                      cores = 4) 
```

### Computing Leave-one-out Cross Validation

```{r}
(loo_cor_1 <- loo(mod_n400_cor_1))
```

```{r}
(loo_cor_0 <- loo(mod_n400_cor_0))
```

```{r}
(loo_comparison_cor <- loo_compare(loo_cor_1, loo_cor_0))
```


## Cross validation for distributional model

```{r}
prior_0dis_2 <- c(prior(normal(0, 10), class = Intercept), # grand mean
                prior(normal(0, 10), class = b, coef = conditionunrelated), # grand beta
                prior(normal(0, log(3)), class = Intercept, dpar = sigma),
                prior(normal(0, 1), class = sd, group = participant_id, dpar = sigma), 
                prior(normal(0, 20), class = sd, coef = Intercept, group = participant_id), # between person variation in mean 
                prior(normal(0, 20), class = sd, coef = conditionunrelated, group = participant_id), # between person variation in slope
                prior(lkj(2), class = cor, group = participant_id)) # correlation between random intercept and random slope
```

### Model 1

```{r}
mod_n400_dis_1 <- brm(brmsformula(N400 ~ 1 + condition + (1 + condition | participant_id), sigma ~ 1 + (1 | participant_id)),
                      data = trials_cond, 
                      prior = prior_0dis_2,
                      family = gaussian(), # default
                      iter = 4000,
                      warmup = 1000,
                      cores = 4) 
```

### Setting up model 0

```{r}
mod_n400_dis_0 <- brm(brmsformula(N400 ~ 1 + (1 + condition | participant_id), sigma ~ 1 + (1 | participant_id)),
                      data = trials_cond, 
                      prior = prior_0dis_2[prior_0cor$class != "b", ],
                      family = gaussian(), # default
                      iter = 4000,
                      warmup = 1000,
                      cores = 4) 
```

### Computing Leave-one-out Cross Validation

```{r}
(loo_dis_1 <- loo(mod_n400_dis_1))
```

```{r}
(loo_dis_0 <- loo(mod_n400_dis_0))
```

```{r}
(loo_comparison_dis <- loo_compare(loo_dis_1, loo_dis_0))
```

## Comparison of Correlation vs. Distributional Model

```{r}
loo_compare(loo_dis_1, loo_cor_1)
```
